/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  GovernorGovernanceLogicV1,
  GovernorGovernanceLogicV1Interface,
} from "../../../../../../contracts/deprecated/V1/governance/libraries/GovernorGovernanceLogicV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "GovernorOnlyExecutor",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122014a4ff70f050078f02bcfdb83637ad1fcc87f3369cce9ad075640543658470b364736f6c63430008140033";

type GovernorGovernanceLogicV1ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GovernorGovernanceLogicV1ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GovernorGovernanceLogicV1__factory extends ContractFactory {
  constructor(...args: GovernorGovernanceLogicV1ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      GovernorGovernanceLogicV1 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): GovernorGovernanceLogicV1__factory {
    return super.connect(runner) as GovernorGovernanceLogicV1__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GovernorGovernanceLogicV1Interface {
    return new Interface(_abi) as GovernorGovernanceLogicV1Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): GovernorGovernanceLogicV1 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as GovernorGovernanceLogicV1;
  }
}
