/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IB3TR } from "./IB3TR";
export type { IB3TRGovernorV1 } from "./IB3TRGovernorV1";
export type { IEmissionsV1 } from "./IEmissionsV1";
export type { IGalaxyMemberV1 } from "./IGalaxyMemberV1";
export type { INodeManagementV1 } from "./INodeManagementV1";
export type { IVeBetterPassportV1 } from "./IVeBetterPassportV1";
export type { IVoterRewardsV1 } from "./IVoterRewardsV1";
export type { IX2EarnAppsV1 } from "./IX2EarnAppsV1";
export type { IX2EarnRewardsPoolV1 } from "./IX2EarnRewardsPoolV1";
export type { IXAllocationPoolV1 } from "./IXAllocationPoolV1";
export type { IXAllocationVotingGovernorV1 } from "./IXAllocationVotingGovernorV1";
