/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVeDelegateVotes,
  IVeDelegateVotesInterface,
} from "../../../contracts/interfaces/IVeDelegateVotes";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "availableVotes",
        type: "uint256",
      },
      {
        internalType: "uint8[]",
        name: "percentages",
        type: "uint8[]",
      },
    ],
    name: "calculateVoteWeights",
    outputs: [
      {
        internalType: "uint256[]",
        name: "voteWeights",
        type: "uint256[]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "_appIds",
        type: "bytes32[]",
      },
      {
        internalType: "uint8[]",
        name: "_percentages",
        type: "uint8[]",
      },
    ],
    name: "castVotes",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
    ],
    name: "getVotes",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "ids",
            type: "bytes32[]",
          },
          {
            internalType: "uint8[]",
            name: "percentages",
            type: "uint8[]",
          },
        ],
        internalType: "struct IVeDelegateVotes.Vote",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "voters",
        type: "address[]",
      },
    ],
    name: "getVotesWithFallback",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "ids",
            type: "bytes32[]",
          },
          {
            internalType: "uint8[]",
            name: "percentages",
            type: "uint8[]",
          },
        ],
        internalType: "struct IVeDelegateVotes.Vote",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVeDelegateVotes__factory {
  static readonly abi = _abi;
  static createInterface(): IVeDelegateVotesInterface {
    return new Interface(_abi) as IVeDelegateVotesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVeDelegateVotes {
    return new Contract(address, _abi, runner) as unknown as IVeDelegateVotes;
  }
}
