AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Get Privy Embedded Wallet Details

    This lambda function is used to get the embedded wallet details for a given wallet address.

Globals:
    Function:
        Timeout: 30
        LoggingConfig:
            LogFormat: JSON
        Environment:
            Variables:
                PRIVY_APP_ID: !Ref PrivyAppId
                PRIVY_APP_SECRET: !Ref PrivyAppSecret
                USERCHECK_API_KEY: !Ref UserCheckApiKey

Resources:
    GetEmbeddedWalletDetailsFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./
            Handler: index.lambdaHandler
            Runtime: nodejs20.x
            Architectures:
                - arm64
            Events:
                GetEmbeddedWalletDetails:
                    Type: Api
                    Properties:
                        RestApiId: !Ref MyApi
                        Path: /v1/embedded_wallet/{walletAddress}/details
                        Method: get
                        Auth:
                            ApiKeyRequired: true
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - index.ts

    MyApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Name: !Sub ${AWS::StackName}-Api
            EndpointConfiguration: REGIONAL
            Auth:
                ApiKeyRequired: true
            DefinitionBody:
                openapi: 3.0.1
                info:
                    title: Get Embedded Wallet Details
                    version: 1.0
                security:
                    - api_key: []
                components:
                    securitySchemes:
                        api_key:
                            type: apiKey
                            name: x-api-key
                            in: header
                paths:
                    /v1/embedded_wallet/{walletAddress}/details:
                        get:
                            summary: Get identifiers for a user via Privy wallet address
                            security:
                                - api_key: []
                            parameters:
                                - name: walletAddress
                                  in: path
                                  required: true
                                  schema:
                                      type: string
                            responses:
                                '200':
                                    description: Success
                                    content:
                                        application/json:
                                            schema:
                                                type: object
                                                additionalProperties: true
                                '404':
                                    description: User not found
                                '422':
                                    description: Missing walletAddress path parameter
                                '500':
                                    description: Internal server error
                            x-amazon-apigateway-integration:
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetEmbeddedWalletDetailsFunction.Arn}/invocations
                                httpMethod: POST
                                type: aws_proxy

    ApiKey:
        Type: AWS::ApiGateway::ApiKey
        DependsOn: MyApi
        Properties:
            Name: !Sub ${AWS::StackName}-ApiKey
            Description: API Key for accessing the API
            Enabled: true
            StageKeys:
                - RestApiId: !Ref MyApi
                  StageName: Prod

    UsagePlan:
        Type: AWS::ApiGateway::UsagePlan
        DependsOn: [MyApi, ApiKey]
        Properties:
            UsagePlanName: !Sub ${AWS::StackName}-UsagePlan
            ApiStages:
                - ApiId: !Ref MyApi
                  Stage: Prod
            Quota:
                Limit: 5000
                Period: MONTH
            Throttle:
                BurstLimit: 200
                RateLimit: 100

    UsagePlanKey:
        Type: AWS::ApiGateway::UsagePlanKey
        DependsOn: [UsagePlan, ApiKey]
        Properties:
            KeyId: !Ref ApiKey
            KeyType: API_KEY
            UsagePlanId: !Ref UsagePlan

Parameters:
    PrivyAppId:
        Type: String
        Description: Privy App ID
        NoEcho: true

    PrivyAppSecret:
        Type: String
        Description: Privy App Secret
        NoEcho: true

    UserCheckApiKey:
        Type: String
        Description: Usercheck API Key
        NoEcho: true

Outputs:
    GetEmbeddedWalletDetailsApi:
        Description: API Gateway endpoint URL for Prod stage for Get Embedded Wallet Details
        Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/v1/embedded_wallet/{walletAddress}/details'
