AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Get Privy Embedded Wallet Details

  This lambda function is used to get the embedded wallet details for a given wallet address.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        PRIVY_APP_ID: !Ref PrivyAppId
        PRIVY_APP_SECRET: !Ref PrivyAppSecret

Resources:
  GetEmbeddedWalletDetailsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: index.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - arm64
      Events:
        GetEmbeddedWalletDetails:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /embedded_wallet/{walletAddress}/details
            Method: get
            Auth:
              ApiKeyRequired: true
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - index.ts

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub ${AWS::StackName}-ApiKey
      Description: API Key for accessing the API
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ServerlessRestApi
          StageName: !Ref ServerlessRestApiProdStage

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub ${AWS::StackName}-UsagePlan
      ApiStages:
        - ApiId: !Ref ServerlessRestApi
          Stage: !Ref ServerlessRestApiProdStage
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 200
        RateLimit: 100

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Parameters:
  PrivyAppId:
    Type: String
    Description: Privy App ID
    NoEcho: true
  PrivyAppSecret:
    Type: String
    Description: Privy App Secret
    NoEcho: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetEmbeddedWalletDetailsApi:
    Description: API Gateway endpoint URL for Prod stage for Get Embedded Wallet Details
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/embedded_wallet/{walletAddress}/details"
